In [11]:
# pip install python-docx

from docx import Document

In [12]:
file_path=r"C:\Users\anchsingh\Anchal Singh\Data Analysis with Python\Doc_Example.docx"

document=Document(file_path)

In [13]:
#reading only the first table

table= document.tables[0]

#table 2
Table_2= document.tables[1]

In [14]:
#loop for reading the data from 1st table

In [15]:
for row in table.rows:
    for cell in row.cells:
        print(cell.text)

Id
Name
Dep ID
DOJ

In [17]:
#loop for reading the data from 2nd table

In [18]:
for row in Table_2.rows:
    for cell in row.cells:
        print(cell.text)

Id
Dep
Manager

In [19]:
# for table in document.tables:
#     for row in table.rows:
#         for cell in row.cells:
#             print(cell.text)

# Inline code , Lambda Function

In [21]:
import pandas as pd

In [22]:
data = [[cell.text for cell in row.cells] for row in table.rows] 
df = pd.DataFrame(data)

In [23]:
#spliting data with : as in table values are written as  Name:  Value

In [24]:
a=df[0].str.split(':',expand=True)
b=df[1].str.split(':',expand=True)

In [25]:
#left of : should be column name and and at right is the record therefore transpose to make it column

In [26]:
a=a.T

b=b.T

In [28]:
#combining the 2 data frame which is transposed vertically

data= pd.concat([a,b],axis=1)

In [29]:
#header currently is index, making 1st row as header

data=pd.DataFrame(data)

In [ ]:
#1st row as header -  selecting first row 

new_header_tbl2=Table_2.iloc[0]

In [ ]:
#selecting data excluding first row
Table_2=Table_2[1:]

In [ ]:
#assigning 1st row as header

Table_2.columns=new_header_tbl2

In [ ]:
final_data['Name']=final_data['CTR Name'].ffill()

# Group By

In [31]:
import pandas as pd

In [32]:
data ={
    'Name':['A','B','C','D','A'],
    'Age':[12,13,45,12,45],
    'Marks':[23,56,78,89,78]
}

In [33]:
data=pd.DataFrame(data)

In [34]:
data

  Name  Age  Marks
0    A   12     23
1    B   13     56
2    C   45     78
3    D   12     89
4    A   45     78

In [35]:
a=data.groupby(['Name'], as_index=False).mean()

In [36]:
a

  Name   Age  Marks
0    A  28.5   50.5
1    B  13.0   56.0
2    C  45.0   78.0
3    D  12.0   89.0